LABEL_RANKING = 'label_ranking'
DYAD_RANKING = 'dyad_ranking'
OBJECT_RANKING = 'object_ranking'
DISCRETE_CHOICE = "discrete_choice"
CHOICE_FUNCTIONS = "choice_functions"
EXCEPTION_RANKINGS_FEATURES_INSTANCES = "Number of instances inconsistent for {} dataset! rankings:{} instances and features arrays:{} instances"
EXCEPTION_OBJECT_ARRAY_SHAPE = "Invalid shape for {} dataset objects features array! shape is: {}"
EXCEPTION_CONTEXT_ARRAY_SHAPE = "Invalid shape for {} dataset context features array! shape is: {}"
EXCEPTION_UNWANTED_CONTEXT_FEATURES = "Unwanted extra context features in {} dataset"
EXCEPTION_RANKINGS_FEATURES_NO_OF_OBJECTS = "Number of objects inconsistent! in rankings:{} objects and features array: {} objects"
EXCEPTION_RANKINGS = "Unwanted rankings in {} dataset"
EXCEPTION_SET_INCLUSION = "Set inclusion binary code not present for all the objects in the set."

IMAGE_DATASET = 'image_dataset'
SUSHI = 'sushi'
SYNTHETIC_OR = 'synthetic_or'
SYNTHETIC_CHOICE = 'synthetic_choice'
HYPER_VOLUME = "hyper_volume"
MNIST = "mnist"
DEPTH = 'depth'
SENTENCE_ORDERING = "sentence_ordering"
LETOR = "letor"
RANKSVM = 'ranksvm'
ERR = 'err'
CMPNET = "cmpnet"
RANKNET = 'ranknet'
FETA_RANKER = 'feta_ranker'
FATE_RANKER = "fate_ranker"
LIST_NET = 'listnet'
FETA_CHOICE = 'feta_choice'
FATE_CHOICE = "fate_choice"
TAG_GENOME = 'tag_genome'
