name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [ '3.8' ]
            env:
              - TOXENV: test1
              - TOXENV: test2
              - TOXENV: test3
              - TOXENV: lint
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install tox==3.23.0
    - run: pip install poetry==1.1.4
    - run: tox
